---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/kyverno/charts
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 6h
  releaseName: kyverno
  targetNamespace: kyverno
  chart:
    spec:
      chart: kyverno
      version: 2.x
      interval: 24h
      sourceRef:
        kind: HelmRepository
        name: kyverno
  values:
    replicaCount: 2
